-- Módulo 09 - Seguridad, auditoría ampliada y datos demo
-- Se agregan acciones de bitácora para trazabilidad municipal y SaaS.

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TENANT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AREA_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AREA_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AREA_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OFICIO_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OFICIO_VIEWED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OFICIO_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OFICIO_CLOSED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OFICIO_FILE_DOWNLOADED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SEGUIMIENTO_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DEMO_DATA_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SECURITY_ACCESS_DENIED';

CREATE INDEX IF NOT EXISTS "audit_logs_tenantId_createdAt_idx" ON "audit_logs"("tenantId", "createdAt");
CREATE INDEX IF NOT EXISTS "audit_logs_entity_entityId_idx" ON "audit_logs"("entity", "entityId");
